# Uncomment this line to define a global platform for your project
use_frameworks!
platform :ios, '9.0'
inhibit_all_warnings!

source 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git' # need to be first 
source 'https://github.com/CocoaPods/Specs.git'

def main
    pod 'SalesforceSDKCore', '~> 4.2.0'
    pod 'SalesforceNetwork', '~> 4.2.0'
    pod 'SalesforceRestAPI', '~> 4.2.0'
    pod 'SmartStore', '~> 4.2.0'
    pod 'SmartSync', '~> 4.2.0'
    
    ui_dependencies
end

def ui_dependencies
    pod 'WYPopoverController', git: 'https://github.com/nicolaschengdev/WYPopoverController.git', branch: 'master', submodules: true
end

target 'TestSalesForce' do
    main
end

# Important Advisory: SQLCipher with Xcode 9 and new SDKs
# https://discuss.zetetic.net/t/important-advisory-sqlcipher-with-xcode-9-and-new-sdks/2371
post_install do | installer |
    print "SQLCipher: link Pods/Headers/sqlite3.h"
    system "mkdir -p Pods/Headers/Private && ln -s ../../SQLCipher/sqlite3.h Pods/Headers/Private"
end
